---
abstract: 'Files and code for building Perl 5.12.2'
author:
  - 'Curtis Jewell <CSJewell@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.33
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Dist-Strawberry-BuildPerl-5122
provides:
  Perl::Dist::Strawberry::BuildPerl::5122:
    file: lib/Perl/Dist/Strawberry/BuildPerl/5122.pm
    version: 2.11_10
requires:
  File::ShareDir: 1.02
  Moose::Role: 0.90
  Perl::Dist::Strawberry: 2.11_10
  perl: 5.010
resources:
  IRC: irc://irc.perl.org/#win32
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Dist-Strawberry-BuildPerl-5122
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Dist-Strawberry-BuildPerl-5122/
version: 2.11_10
